name: Run Playwright Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SIRIUSXM_USERNAME: ${{ secrets.SIRIUSXM_USERNAME }}
      SIRIUSXM_PASSWORD: ${{ secrets.SIRIUSXM_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run tests
        run: pytest
